### ISSUE TITLE
hosts file reloading is unsafe

### ISSUE THREAD

**Issue by nothingmuch** [alash3al/httpsify#10]
The `HOSTS` map is [updated in place](https://github.com/alash3al/httpsify/blob/11368d45b52351929f6ed88aa3558ef0bbad6b96/hosts.go#L35) when the hosts file is updated, with a [simple mutex](https://github.com/alash3al/httpsify/blob/11368d45b52351929f6ed88aa3558ef0bbad6b96/hosts.go#L21-L22) but unfortunately it may be concurrently accessed ([1](https://github.com/alash3al/httpsify/blob/11368d45b52351929f6ed88aa3558ef0bbad6b96/server.go#L27),[2](https://github.com/alash3al/httpsify/blob/11368d45b52351929f6ed88aa3558ef0bbad6b96/server.go#L62)) during such an update.

Secondly, decoding JSON into the `HOSTS` map will only overwrite existing entries, so deleted entries will persist, and type errors may leave the map in an inconsistent state (see [playground example](https://play.golang.org/p/bTUFMTdb2yz)).

The mutex should also be to changed to an RWMutex, with the shared locks for the read operations and a write lock for the reloading.

Instead of decoding the file into `&HOSTS`, directly a new map should be allocated, and then assigned to the `HOSTS` variable. The write mutex can be obtained after the file has been successfully loaded, protecting just the assignment, this would have the additional benefit of reducing lock contention, allowing requests to be handled while the new hosts file is being parsed.

**Comment by alash3al** [comment]
this has been fixed, I'm using `atomic.Value` now
