### ISSUE TITLE
Account creation on ACMEv1 is disabled.

### ISSUE THREAD

**Issue by gkozyrev** [alash3al/httpsify#15]
2019/11/12 05:13:55 http: TLS handshake error from 10.255.0.2:46632: 403 urn:acme:error:unauthorized: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.

**Comment by gkozyrev** [comment]
How can I fix this problem?

**Comment by alash3al** [comment]
I released a version that should fix this: [v3.2](https://github.com/alash3al/httpsify/releases/tag/v3.2)

**Comment by gkozyrev** [comment]
> I released a version that should fix this: [v3.2](https://github.com/alash3al/httpsify/releases/tag/v3.2)

Still getting the same problem

**Comment by fedearne** [comment]
I see the same issue and also, the 3.2 windows build is somehow not correct. Just a bunch of random files instead of an executable.

**Comment by alash3al** [comment]
this issue has been fixed as httpsify v4 is written from scratch, I'll release the v4 tomorrow.
