### ISSUE TITLE
Please use tags for futher releases in docker

### ISSUE THREAD

**Issue by saksmt** [alash3al/httpsify#18]
Just found out that the whole CLI API has changed after updating my cluster resulting in dead container. It would be nice to avoid such a problem in future. There are two main concerns: stability of CLI API and tags for docker images.

P.S. Also readme became obsolete after removal of `--redirect` flag.

**Comment by alash3al** [comment]
I'm sorry @saksmt , I just released that major change and deprecated any old version due to the deprecation of the underlying let's encrypt API.

You're right, I should make use of tags to not to cause any production issue with any production environment.

Sorry again,

**Comment by saksmt** [comment]
Okay then
