### ISSUE TITLE
Path not used?

### ISSUE THREAD

**Issue by phf** [alash3al/httpsify#2]
So things work fine if I use just a domain name ("host" in the lingo of HTTP I guess) but as soon as the URL has a path things stop working. I believe

req, err := http.NewRequest(r.Method, *backend, r.Body)

should really be something like

req, err := http.NewRequest(r.Method, *backend+r.URL.Path, r.Body)

instead. But since I am not much of a HTTP protocol person, I am not 100% sure about this. Any insights?

**Comment by alash3al** [comment]
oops, its my fault, thanks for your notice, i've patched it
but with this `+ r.URL.RequestURI()` instead of `+ r.URL.Path`
