### ISSUE TITLE
Trace/breakpoint trap

### ISSUE THREAD

**Issue by dimzon** [alash3al/httpsify#5]
```
root@nano128:~# ./httpsify  --domains="blablabla.tk"
Trace/breakpoint trap

```

**Comment by alash3al** [comment]
Did you try to build `httpsify` yourself on your own os ?

1- install golang from [here](https://golang.org/dl/)
2- setup your env `$GOPATH`
3- `go get github.com/alash3al/httpsify`
4- `go install github.com/alash3al/httpsify`
5- `httpsify --domains="blablabla.tk"`
