### ISSUE TITLE
Add http redirect to https

### ISSUE THREAD

**Issue by osiloke** [alash3al/httpsify#8]
This will be a useful feature.

**Comment by alash3al** [comment]
But if we did it, we will override the default webserver on the users servers, so I think it is better to do it from there, i.e: let's assume that you have nginx listening on port 80, I will add a rule to nginx to check whether the request is coming from our httpsify "x-forwarded-proto: https" so we won't do anything, else we will redirect the traffic to the https version.

Httpsify sends some useful headers to the backend such as "x-forwarded-for, x-forwarded-proto"

**Comment by osiloke** [comment]
I later came to that conclusion, and just created a small go app that redirects to the ssl endpoint. 
Thanks for your input

**Comment by alash3al** [comment]
@osiloke , there is a new version that automatically redirects http to https with no hassle, just try it.
